---
title: "Gov 50 Final Project"
author: "Alia Al-Wir"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to unemployment in the MENA region. I am particularly interested in exploring the trajectory of unemployment rates since the Arab Spring, since that was a driving factor in many countries. While some countries unemployment rates have dropped, others see even higher rates than before the protests and revolutions started. As such, I would be interested to see if there is a pattern between the effectiveness and changes that emerged post-Arab Spring, and unemployment rates. 

## Milestone 2

Do greater economic concerns and problems correlate to increased mistrust in the government, and how has this changed since the Arab Spring in the Arab states? I will explore how people's economic concerns have shifted in Arab countries and how this relates to how much they trust their government. I hypothesize that prior to the Arab Spring and in its early days, there were significant economic concerns and significant government mistrust. However, as the subsequent revolutions died down, economic apathy decreased and citizens' faith and and hope for their government increased until the pandemic where economic apathy and government mistrust returned. I will rely on data from the Arab Barometer Surveys (https://www.arabbarometer.org/survey-data/). They have seven data sets which consist of surveys conducted with citizens of Arab countries regarding all these factors, and their answers are given on a numerical scale of 1-4. 4 indicates less trust and 1 indicates more trust. The numbers 98 and 99 indicate people who did not know how to answer and refused to answer respectively. I will be able to examine the mean answers to specific questions regarding both economic and government apathy and trust, as well as calculate an overall mean response for these countries. I will also need to omit the 98 and 99 variables when calculating these means and instead calculate what proportion of people refused to give an answer. 
However, one issue I will face is that not all the Arab states were included in all the reports. The most recent report from 2021-2022 contains the largest number of Arab states surveyed at 12, while the first one conducted from 2006-2009 only examines seven states.

```{r}
load("data/ICPSR_35040/DS0001/35040-0001-Data.rda")

load("data/ICPSR_26581/DS0001/26581-0001-Data.rda")

load("data/ICPSR_36273/DS0001/36273-0001-Data.rda")

load("data/ICPSR_37029/DS0001/37029-0001-Data.rda")
```

